version: '3.4'

services:
  bookstoresystem:
    image: ${DOCKER_REGISTRY-}bookstoresystem
    build:
      context: .
      dockerfile: BookStoreSystem/Dockerfile
    ports:
      - "5000:8080"
      - "5001:8081"

  mssql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=DBUser101010
    volumes:
      - sql_data:/var/opt/mssql
    ports:
      - "1434:1433"

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: ["redis-server", "--appendonly", "yes"]

volumes:
  sql_data:
  redis_data:  